//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilirkisilik_Uygulamasi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BILIRKISILIK
    {
        public int ID { get; set; }
        public Nullable<int> BIRIM_ID { get; set; }
        public string DOSYANO { get; set; }
        public Nullable<System.DateTime> GELISTARIHI { get; set; }
        public Nullable<int> RAPORTURU_ID { get; set; }
        public Nullable<bool> DOSYADURUMU { get; set; }
        public Nullable<int> BILIRKISI_ID { get; set; }
        public Nullable<System.DateTime> TESLIMTARIHI { get; set; }
        public Nullable<decimal> UCRET { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public Nullable<bool> UCRETDURUM { get; set; }
        public string NOTLAR { get; set; }
    
        public virtual TBL_BILIRKISILER TBL_BILIRKISILER { get; set; }
        public virtual TBL_BIRIMLER TBL_BIRIMLER { get; set; }
        public virtual TBL_RAPORTURU TBL_RAPORTURU { get; set; }
    }
}
